### ISSUE TITLE
License for tweetnacl-usable

### ISSUE THREAD

**Issue by ghost** [ultramancool/tweetnacl-usable#1]
Hello, I'd like to know if tweenacl-usable's license is intentionally Github's default one ("All Rights Reserved", or "you can view but that's all"), or if you intend to license it differently.

**Comment by ultramancool** [comment]
Whatever the original tweetnacl license is (I believe public domain)
applies. My changes are public domain.

Feel free to use it however you wish.

**Comment by ghost** [comment]
Thank you very much for the clarification.
